# ChatPlugin Configuration File

# General Settings
chat-moderation-enabled: true
use-litebans: true

# Chat Settings
chat-muted: false
mute-message: "&cChat is currently muted by an administrator."
unmute-message: "&aChat has been unmuted."
clear-message: "&eChat has been cleared by an administrator."

# Filter Settings
profanity-filter:
  enabled: true
  replacement-character: "*"
  words:
    - "damn"
    - "hell"
    - "crap"
    - "stupid"
    # Add more words as needed

# Severe violations (results in temporary mute)
severe-violations:
  enabled: true
  mute-duration: 86400 # 24 hours in seconds
  words:
    - "racist"
    - "homophobic"
    - "nazi"
    - "fag"
    - "nigger"
    - "retard"
    # Add more severe words as needed

# Critical violations (results in permanent mute)
critical-violations:
  enabled: true
  detection-patterns:
    ip-addresses: true
    doxing-keywords: true
  keywords:
    - "doxx"
    - "dox"
    - "address"
    - "phone number"
    - "real name"
    - "lives at"
    # Add more doxing-related keywords

# Image Description Settings
image-description:
  enabled: true
  # Whether to replace image URLs with descriptions or append descriptions
  replace-with-description: false
  # Whether to notify the player that their image was described
  notify-player: true

# Messages
messages:
  profanity-filtered: "&eYour message contained inappropriate language and has been filtered."
  severe-violation: "&cYou have been muted for inappropriate language. Duration: %duration%"
  critical-violation: "&4You have been permanently muted for sharing personal information."
  no-permission: "&cYou don't have permission to use this command."
  chat-muted-player: "&cYou cannot send messages while chat is muted."
  player-muted: "&cYou are currently muted and cannot send messages."
  image-described: "&7[Image described: %description%]"

# LiteBans Integration
litebans:
  severe-mute-reason: "Inappropriate language (automated)"
  critical-mute-reason: "Sharing personal information (automated)"
  use-silent-punishments: true

# Internal punishment system (fallback when LiteBans is not available)
internal-punishments:
  data-file: "punishments.yml"
  save-interval: 300 # 5 minutes in seconds