name: ChatPlugin
version: 1.0.0
main: com.lowcjm.chatplugin.ChatPlugin
api-version: 1.21
author: lowcjm
description: A comprehensive chat moderation plugin for Minecraft 1.21+

commands:
  mutechat:
    description: Mute or unmute chat for all players
    usage: /mutechat [mute|unmute]
    permission: chatplugin.mutechat
    aliases: [mc]
  clearchat:
    description: Clear chat for all players
    usage: /clearchat
    permission: chatplugin.clearchat
    aliases: [cc]
  chatmoderation:
    description: Toggle chat moderation system
    usage: /chatmoderation [on|off]
    permission: chatplugin.toggle
    aliases: [cm]
  describeimage:
    description: Manually describe an image from URL
    usage: /describeimage <image_url>
    permission: chatplugin.describe
    aliases: [di, describe]

permissions:
  chatplugin.*:
    description: All ChatPlugin permissions
    children:
      chatplugin.mutechat: true
      chatplugin.clearchat: true
      chatplugin.toggle: true
      chatplugin.bypass: true
      chatplugin.describe: true
    default: op
  chatplugin.mutechat:
    description: Allows muting and unmuting chat
    default: op
  chatplugin.clearchat:
    description: Allows clearing chat
    default: op
  chatplugin.toggle:
    description: Allows toggling moderation system
    default: op
  chatplugin.bypass:
    description: Bypass chat restrictions and filters
    default: op
  chatplugin.describe:
    description: Allows describing images manually
    default: true

soft-depend: [LiteBans]